### ISSUE TITLE
Zephyr Setup for Linux

### ISSUE THREAD

**Issue by kanakshilledar** [maksimdrachov/zephyr-rtos-tutorial#13]
I would like to write the tutorial for zephyr rtos setup for Linux environment. 
Arch Linux to be more specific.
I am also learning zephyr right now.

**Comment by kanakshilledar** [comment]
I am taking up the issue. @kanakshilledar

**Comment by maksimdrachov** [comment]
Hi,

As you might have noticed, I've been busy and so can't put a lot of effort into this tutorial. 

(I might come back to this in the near future, as I think it could be necessary for work to brush up my knowledge of Zephyr)

If you do decide to go ahead, I will gladly review your pull request. :)

**Comment by kanakshilledar** [comment]
Hey! I have written the documentation for the Linux installation part [here](https://github.com/kanakshilledar/zephyr-rtos-tutorial). As I dont have a Nucleo L552ZE-Q board. So for the blinky example I took the ESP32. 
If the content is good I will create a PR. 
Thanks!

**Comment by maksimdrachov** [comment]
Will check this weekend :)

**Comment by maksimdrachov** [comment]
You can already submit PR, if i have any comments Ill put them there.

**Comment by kanakshilledar** [comment]
I created the pr #14 do let me know if there are any changes required. 
thanks :)
