### ISSUE TITLE
Recommended IDE

### ISSUE THREAD

**Issue by tommasoclini** [maksimdrachov/zephyr-rtos-tutorial#23]
What IDE do you recommend for the first steps with Zephyr? Possibly on linux

**Comment by maksimdrachov** [comment]
I use VSCode.

**Comment by maarten1C96** [comment]
Visual Studio Code indeed! You might find the following article useful:

[How to Configure VS Code for Zephyr Development]( https://zephyrproject.org/how-to-configure-vs-code-for-zephyr-development/)

**Comment by tommasoclini** [comment]
I've tried configuring vscode for debugging, but I've found CLion to be a bit easier to work with and slightly faster(even though it's more memory hungry), thank you for the recommendations.
