### ISSUE TITLE
Better layout / theme

### ISSUE THREAD

**Issue by nobodywasishere** [maksimdrachov/zephyr-rtos-tutorial#4]
I believe it would be more accessible if this used a theme such as [Just the Docs](https://github.com/pmarsceill/just-the-docs), which would provide easier navigation and search functionality. (This is something I'm actively working on, at least for myself, and would like to contribute it back if possible).

**Comment by nobodywasishere** [comment]
Here's what I've done so far: https://blog.eowyn.net/zephyr-rtos-tutorial/

**Comment by maksimdrachov** [comment]
Hi,

Agree looks much better. I'm currently too busy with work/other projects to do this, but if you submit a PR I would gladly merge it. :)

Kind regards
Maksim
